### ISSUE TITLE
Remove participants contact number from the analysis

### ISSUE THREAD

**Issue by amitness** [AiDevNepal/grand-design#1]
The analysis makes mobile numbers of some participants public in the output of jupyter notebook. Hiding that column before start of the analysis can solve it.

![untitled](https://user-images.githubusercontent.com/8587189/39408527-672cce84-4bf7-11e8-896b-23e9bf05ef7c.png)

**Comment by NISH1001** [comment]
@amitness Thank you for pointing that out.
